# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GoogleSignInTestApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GoogleSignInTestApp

  target 'GoogleSignInTestAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GoogleSignInTestAppUITests' do
    # Pods for testing
  end

pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'GoogleSignIn'

end
